# Generated by Django 2.2.2 on 2019-06-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190618_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
